import React from "react";
import { Audio, staticFile, AbsoluteFill, interpolate, useCurrentFrame, Easing } from "remotion";
import { Facet } from "../Mascot";
import { Stage, Headline, Kicker, EndCard, Counter, Panel, useBob, useBlink } from "../ui";
import { C, FONT, SPECTRUM } from "../theme";

/**
 * ONE TRADE IN — 26s route-engine explainer.
 *
 * The numbers here are the ones the README documents as a real on-chain
 * result (1 ETH -> USDG on chain 4663). Venues without a pool resolve to
 * "no pool" rather than to a fabricated quote — the product's whole claim is
 * that nothing is mocked, and a promo that invents figures undercuts it.
 * To refresh: pull a live /api/quote and edit ROUTES below. Nothing else
 * in this file needs to change.
 */
const ROUTES = [
  { venue: "Uniswap V2", tier: "direct",   out: 2485.51, best: false },
  { venue: "Uniswap V2", tier: "via WETH", out: null,    best: false },
  { venue: "Uniswap V3", tier: "0.01%",    out: 2498.84, best: true  },
  { venue: "Uniswap V3", tier: "0.05%",    out: null,    best: false },
  { venue: "Uniswap V3", tier: "0.30%",    out: null,    best: false },
  { venue: "Uniswap V3", tier: "1.00%",    out: null,    best: false },
];
const BEST = ROUTES.findIndex((r) => r.best);

const ROW_H = 88, ROW_GAP = 14, ROW_TOP = 236, COL_X = 1076, COL_W = 748;
const REFRACT = { x: 772, y: 566 };

const rowY = (i: number) => ROW_TOP + i * (ROW_H + ROW_GAP);

const T = { orb: 62, throw: 116, hit: 150, rays: 156, cards: 172, resolve: 262, judge: 430, callout: 486, turn: 632, end: 750 };

export const BestRoute: React.FC = () => {
  const f = useCurrentFrame();
  const bob = useBob(8, 92);
  const blink = useBlink(11);

  const enter = interpolate(f, [24, 56], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.out(Easing.cubic) });
  const cx = 190 + enter * 120;
  const cy = 830 + bob;

  // Charge, wind up, throw. The arm leads the orb by a few frames so the
  // release reads as caused by him rather than simultaneous with him.
  const windup = interpolate(f, [T.throw - 22, T.throw], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const release = interpolate(f, [T.throw, T.throw + 12], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const armR = -46 - windup * 34 + release * 96;

  // Orb: forms in his hands, then arcs into the prism.
  const orbBirth = interpolate(f, [T.orb, T.orb + 26], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.out(Easing.back(2)) });
  const flight = interpolate(f, [T.throw + 6, T.hit], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.in(Easing.quad) });
  const ox0 = cx + 108, oy0 = cy - 42;
  // Quadratic arc, apex lifted above the straight line so the toss has weight.
  const bez = (a: number, b: number, c: number, t: number) => (1 - t) ** 2 * a + 2 * (1 - t) * t * b + t * t * c;
  const orbX = bez(ox0, (ox0 + REFRACT.x) / 2, REFRACT.x, flight);
  const orbY = bez(oy0, oy0 - 190, REFRACT.y + 10, flight);
  const orbVisible = f > T.orb && f < T.hit + 3;

  const hit = interpolate(f, [T.hit - 2, T.hit + 4, T.hit + 26], [0, 1, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const prismIn = interpolate(f, [T.throw - 30, T.throw + 4], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.out(Easing.cubic) });

  const judged = interpolate(f, [T.judge, T.judge + 26], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const beat2 = interpolate(f, [T.callout, T.callout + 22], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const turn = interpolate(f, [T.turn, T.turn + 20], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const outro = interpolate(f, [T.end - 14, T.end + 6], [1, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });

  const expression =
    f < T.orb ? "idle" :
    f < T.throw ? "focus" :
    f < T.judge + 10 ? "wow" :
    "cheer";

  return (
    <Stage>
      {/* Original score, generated by music/compose.mjs and cued to this
          scene's frame constants. Swap the file to use a licensed track. */}
      <Audio src={staticFile("music/refract-best-route.wav")} />
      <AbsoluteFill style={{ opacity: outro }}>
        {/* ---- headline slot ------------------------------------------
             All three beats share one position and cross-fade: the question,
             the number, then the claim. Stacking them here keeps the whole
             lower-left clear for Facet, which is where he needs to be to
             throw into the prism. ---------------------------------------- */}
        <div style={{ position: "absolute", left: 108, top: 92, width: 980 }}>
          <div style={{ opacity: 1 - beat2, position: "absolute", width: 940 }}>
            <Kicker delay={0}>The route engine</Kicker>
            <div style={{ marginTop: 20 }}>
              <Headline delay={8} size={112}>ONE TRADE IN.</Headline>
            </div>
          </div>

          <div style={{ opacity: beat2 * (1 - turn), position: "absolute", width: 940, transform: `translateY(${(1 - beat2) * 24}px)` }}>
            <Kicker delay={T.callout} color={C.olive}>You receive</Kicker>
            <div style={{ marginTop: 12, display: "flex", alignItems: "baseline", gap: 28 }}>
              <Counter to={2498.84} delay={T.callout + 6} duration={40} size={124} color={C.gold} />
              <span style={{ fontFamily: FONT.display, fontSize: 54, color: C.muted, fontWeight: 600 }}>USDG</span>
            </div>
            <div style={{ marginTop: 16, display: "flex", alignItems: "center", gap: 16, opacity: interpolate(f, [T.callout + 44, T.callout + 64], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" }) }}>
              <span style={{ fontFamily: FONT.mono, fontSize: 27, color: C.olive, border: `1px solid ${C.olive}`, borderRadius: 9, padding: "8px 15px", fontWeight: 600 }}>
                +0.54%
              </span>
              <span style={{ fontFamily: FONT.body, fontSize: 27, color: C.muted }}>
                over the V2 route — found, not guessed.
              </span>
            </div>
          </div>

          <div style={{ opacity: turn, position: "absolute", width: 940, transform: `translateY(${(1 - turn) * 24}px)` }}>
            <Kicker delay={T.turn}>Every venue quoted</Kicker>
            <div style={{ marginTop: 20 }}>
              <Headline delay={T.turn + 6} size={112}>BEST ROUTE WINS.</Headline>
            </div>
            <div style={{ marginTop: 26, width: 820, fontFamily: FONT.body, fontSize: 26, color: C.muted, opacity: interpolate(f, [T.turn + 34, T.turn + 56], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" }) }}>
              You can always override the pick. The engine recommends; it never hides.
            </div>
          </div>
        </div>

        {/* ---- beams, prism, rays ---- */}
        <svg width={1920} height={1080} style={{ position: "absolute", inset: 0 }}>
          <defs>
            <linearGradient id="br-face" x1={REFRACT.x} y1={REFRACT.y - 110} x2={REFRACT.x} y2={REFRACT.y + 110} gradientUnits="userSpaceOnUse">
              <stop offset="0%" stopColor={C.honey} stopOpacity={0.34} />
              <stop offset="100%" stopColor={C.bronze} stopOpacity={0.07} />
            </linearGradient>
          </defs>

          {/* prism */}
          <g opacity={prismIn} transform={`translate(${REFRACT.x} ${REFRACT.y}) scale(${0.86 + prismIn * 0.14}) translate(${-REFRACT.x} ${-REFRACT.y})`}>
            <path
              d={`M${REFRACT.x} ${REFRACT.y - 118} L${REFRACT.x + 104} ${REFRACT.y + 108} H${REFRACT.x - 104} Z`}
              fill="url(#br-face)" stroke={C.gold} strokeWidth={2.6} strokeLinejoin="round"
              opacity={0.55 + hit * 0.45}
            />
          </g>
          {hit > 0 ? <circle cx={REFRACT.x} cy={REFRACT.y} r={40 + hit * 130} fill={C.honey} opacity={hit * 0.35} /> : null}

          {/* One ray per venue, landing exactly on its row. Dead venues fade
              back once the quotes resolve, so the eye is walked to the winner. */}
          {ROUTES.map((r, i) => {
            const p = interpolate(f, [T.rays + i * 7, T.rays + i * 7 + 26], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.out(Easing.cubic) });
            if (p <= 0) return null;
            const x1 = REFRACT.x + 60, y1 = REFRACT.y + 4;
            const x2 = COL_X - 16, y2 = rowY(i) + ROW_H / 2;
            const dim = r.out === null ? judged * 0.78 : 0;
            return (
              <line
                key={i}
                x1={x1} y1={y1}
                x2={x1 + (x2 - x1) * p} y2={y1 + (y2 - y1) * p}
                stroke={SPECTRUM[i]} strokeWidth={r.best ? 6 : 4} strokeLinecap="round"
                opacity={(r.best ? 1 : 0.9) * (1 - dim)}
              />
            );
          })}

          {/* the ETH the user actually put in */}
          {orbVisible ? (
            <g opacity={orbBirth}>
              <circle cx={orbX} cy={orbY} r={44} fill={C.honey} opacity={0.22} />
              <circle cx={orbX} cy={orbY} r={26} fill="#fbfff6" />
              <circle cx={orbX} cy={orbY} r={26} fill="none" stroke={C.gold} strokeWidth={3} />
            </g>
          ) : null}
        </svg>

        {orbVisible ? (
          <div style={{ position: "absolute", left: orbX - 90, top: orbY - 78, width: 180, textAlign: "center", fontFamily: FONT.mono, fontSize: 26, color: C.honey, opacity: orbBirth * (1 - flight * 1.4), letterSpacing: "0.1em" }}>
            1 ETH
          </div>
        ) : null}

        {/* ---- mascot ---- */}
        <div style={{ position: "absolute", left: cx - 190, top: cy - 207, opacity: enter }}>
          <Facet
            size={380} expression={expression as never} blink={blink}
            lookX={f > T.throw ? 5 : 2} lookY={f > T.rays && f < T.judge ? -2 : 0}
            armL={-18} armR={armR} tilt={Math.sin(f / 80) * 2 - windup * 5}
            glow={0.4 + hit * 0.5} charge={0.4 + (f > T.orb && f < T.hit ? 0.55 : 0.2)}
            uid="br"
          />
        </div>

        {/* ---- the quote table ---- */}
        {ROUTES.map((r, i) => {
          const lift = interpolate(f, [T.cards + i * 11, T.cards + i * 11 + 22], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.out(Easing.cubic) });
          if (lift <= 0) return null;
          const resolved = interpolate(f, [T.resolve + i * 18, T.resolve + i * 18 + 14], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
          const dead = r.out === null;
          const win = r.best;
          const dim = dead ? 1 - judged * 0.68 : win ? 1 : 1 - judged * 0.42;
          const scale = win ? 1 + judged * 0.045 : 1;

          return (
            <div key={i} style={{ position: "absolute", left: COL_X, top: rowY(i), width: COL_W, height: ROW_H, opacity: dim, transform: `scale(${scale})`, transformOrigin: "0% 50%" }}>
              <Panel lift={lift} highlight={win && judged > 0.4} style={{ height: "100%", display: "flex", alignItems: "center", padding: "0 28px", gap: 20 }}>
                <span style={{ width: 10, height: 10, borderRadius: 5, background: SPECTRUM[i], boxShadow: `0 0 14px ${SPECTRUM[i]}` }} />
                <div style={{ display: "flex", flexDirection: "column", gap: 4, minWidth: 240 }}>
                  <span style={{ fontFamily: FONT.display, fontSize: 29, color: C.text, fontWeight: 600 }}>{r.venue}</span>
                  <span style={{ fontFamily: FONT.mono, fontSize: 19, color: C.faint, letterSpacing: "0.12em" }}>{r.tier.toUpperCase()}</span>
                </div>
                <div style={{ flex: 1, textAlign: "right", fontFamily: FONT.mono, fontSize: 34, fontVariantNumeric: "tabular-nums" }}>
                  {resolved < 0.5 ? (
                    <span style={{ color: C.faint, fontSize: 24, letterSpacing: "0.14em" }}>
                      QUOTING{".".repeat(1 + (Math.floor(f / 6) % 3))}
                    </span>
                  ) : dead ? (
                    <span style={{ color: C.faint, fontSize: 24, letterSpacing: "0.1em" }}>NO POOL</span>
                  ) : (
                    <span style={{ color: win ? C.gold : C.muted, fontWeight: 600 }}>
                      {r.out!.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                    </span>
                  )}
                </div>
                {win && judged > 0.5 ? (
                  <span style={{ fontFamily: FONT.mono, fontSize: 18, letterSpacing: "0.16em", color: "#0b1400", background: C.gold, padding: "7px 13px", borderRadius: 8, fontWeight: 700 }}>
                    BEST
                  </span>
                ) : null}
              </Panel>
            </div>
          );
        })}

      </AbsoluteFill>

      {f >= T.end ? <EndCard delay={T.end} tagline="Every venue on the chain, quoted at request time." /> : null}
    </Stage>
  );
};
