import React from "react";
import { Audio, staticFile, AbsoluteFill, interpolate, useCurrentFrame, random, Easing } from "remotion";
import { Facet, Fan } from "../Mascot";
import { Stage, Headline, Kicker, EndCard, Counter, Panel, useBob, useBlink } from "../ui";
import { C, FONT, SPECTRUM } from "../theme";

/**
 * YOU ROUTED IT, YOU EARN IT — 19s rewards film.
 *
 * The hero figure is the rate (0.12%), not a balance: the distributor is not
 * deployed yet, so a claimable number on screen would be a lie. The worked
 * example is labelled as one, and the film says plainly that nothing settles
 * yet — same posture the Rewards page takes.
 */

const T = { facet: 40, fan: 66, rain: 92, rate: 132, example: 268, honest: 392, end: 470 };
const SHARDS = 26;

/** One falling spectrum shard. Seeded per index so the rain is deterministic. */
const Shard: React.FC<{ i: number; frame: number; landY: number }> = ({ i, frame, landY }) => {
  const seed = `shard-${i}`;
  const startX = 1150 + random(seed) * 620;
  const drift = (random(seed + "d") - 0.5) * 130;
  const delay = T.rain + random(seed + "t") * 250;
  const dur = 62 + random(seed + "u") * 34;
  const size = 15 + random(seed + "s") * 13;
  const spin = (random(seed + "r") - 0.5) * 760;

  const t = interpolate(frame, [delay, delay + dur], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.in(Easing.quad) });
  if (t <= 0) return null;

  const x = startX + drift * t;
  const y = 250 + (landY - 250) * t;
  // A shard that has landed settles into the pile instead of vanishing.
  const settled = t >= 1;
  const opacity = settled ? interpolate(frame, [delay + dur, delay + dur + 26], [1, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" }) : 1;
  const color = SPECTRUM[i % SPECTRUM.length];

  return (
    <g transform={`translate(${x} ${y}) rotate(${spin * t}) scale(${settled ? 1 - (1 - opacity) * 0.4 : 1})`} opacity={opacity}>
      <path d={`M0 ${-size} L${size * 0.9} ${size * 0.7} H${-size * 0.9} Z`} fill={color} stroke={color} strokeWidth={size * 0.5} strokeLinejoin="round" opacity={0.95} />
    </g>
  );
};

export const Cashback: React.FC = () => {
  const f = useCurrentFrame();
  const bob = useBob(9, 88);
  const blink = useBlink(29);

  const enter = interpolate(f, [T.facet, T.facet + 30], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.out(Easing.cubic) });
  const cx = 1420, cy = 700 + bob;
  const fanP = interpolate(f, [T.fan, T.fan + 40], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });

  // Arms up and catching, with a small alternating reach so he looks busy.
  const reach = Math.sin(f / 17) * 13;
  const outro = interpolate(f, [T.end - 14, T.end + 6], [1, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });

  const pileH = interpolate(f, [T.rain + 40, T.rain + 300], [0, 74], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });

  return (
    <Stage>
      {/* Original score, generated by music/compose.mjs and cued to this
          scene's frame constants. Swap the file to use a licensed track. */}
      <Audio src={staticFile("music/refract-cashback.wav")} />
      <AbsoluteFill style={{ opacity: outro }}>
        <svg width={1920} height={1080} style={{ position: "absolute", inset: 0 }}>
          {/* The spectrum overhead is the routed flow; the shards are the slice
              that comes back to the wallet that generated it. */}
          <Fan x={1010} y={188} length={860} spread={44} progress={fanP} width={7} opacity={0.85} />
          {Array.from({ length: SHARDS }, (_, i) => (
            <Shard key={i} i={i} frame={f} landY={cy + 40} />
          ))}
          {/* the pile he has caught */}
          <ellipse cx={cx} cy={cy + 168} rx={128} ry={pileH * 0.34} fill={C.brass} opacity={0.3} />
          <ellipse cx={cx} cy={cy + 160} rx={104 * (pileH / 74)} ry={pileH * 0.28} fill={C.gold} opacity={0.55} />
        </svg>

        <div style={{ position: "absolute", left: cx - 190, top: cy - 207, opacity: enter, transform: `scale(${0.9 + enter * 0.1})` }}>
          <Facet
            size={380}
            expression={f > T.rain + 30 ? "cheer" : "happy"}
            blink={blink}
            lookY={f > T.rain ? -4 : 0}
            lookX={Math.sin(f / 19) * 3}
            armL={-96 - reach} armR={-96 + reach}
            tilt={Math.sin(f / 74) * 2}
            glow={0.5} charge={0.5 + Math.sin(f / 26) * 0.25}
            uid="cb"
          />
        </div>

        {/* ---- copy ---- */}
        <div style={{ position: "absolute", left: 108, top: 132, width: 900 }}>
          <Kicker delay={0}>Rewards</Kicker>
          <div style={{ marginTop: 22 }}>
            <Headline delay={8} size={104}>YOU ROUTED IT. YOU EARN IT.</Headline>
          </div>
        </div>

        {f > T.rate ? (
          <div style={{ position: "absolute", left: 108, top: 416 }}>
            <Counter to={0.12} delay={T.rate} duration={34} decimals={2} suffix="%" size={152} color={C.gold} />
            <div
              style={{
                marginTop: 20, width: 680, fontFamily: FONT.body, fontSize: 29, color: C.muted, lineHeight: 1.35,
                opacity: interpolate(f, [T.rate + 24, T.rate + 44], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" }),
              }}
            >
              of routed volume, attributed back to the wallet that generated it.
            </div>
          </div>
        ) : null}

        {f > T.example ? (
          <div style={{ position: "absolute", left: 108, top: 752, width: 830 }}>
            <Panel lift={interpolate(f, [T.example, T.example + 24], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" })} style={{ padding: "26px 32px" }}>
              <div style={{ fontFamily: FONT.mono, fontSize: 17, letterSpacing: "0.24em", color: C.faint, marginBottom: 16 }}>WORKED EXAMPLE</div>
              <div style={{ display: "flex", alignItems: "center", gap: 22, fontFamily: FONT.mono, fontSize: 32, color: C.text, whiteSpace: "nowrap" }}>
                <span>250 ETH routed</span>
                <span style={{ color: C.gold, fontSize: 30 }}>&#8594;</span>
                <Counter to={0.3} delay={T.example + 18} duration={30} decimals={2} suffix=" ETH" size={32} color={C.olive} />
                <span style={{ fontSize: 24, color: C.faint }}>accrued</span>
              </div>
            </Panel>
          </div>
        ) : null}

        {f > T.honest ? (
          <div
            style={{
              position: "absolute", left: 108, top: 906, width: 900,
              fontFamily: FONT.body, fontSize: 24, color: C.muted, lineHeight: 1.45,
              opacity: interpolate(f, [T.honest, T.honest + 22], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" }),
              borderLeft: `2px solid ${C.line}`, paddingLeft: 22,
            }}
          >
            It accrues from your real swap events on chain. It is not claimable yet —
            the distributor is not deployed, and the app says so rather than showing
            a balance that does not exist.
          </div>
        ) : null}
      </AbsoluteFill>

      {f >= T.end ? <EndCard delay={T.end} tagline="Auditable by anyone, against the chain." /> : null}
    </Stage>
  );
};
