import React from "react";
import { Audio, staticFile, AbsoluteFill, interpolate, useCurrentFrame, Easing } from "remotion";
import { Facet, Fan } from "../Mascot";
import { Stage, Headline, Kicker, EndCard, useBob, useBlink } from "../ui";
import { C, FONT } from "../theme";

/**
 * MEET FACET — 12s brand bumper.
 *
 * A beam of white light travels in, condenses into the mascot, and leaves as a
 * spectrum. That is the product in one gesture: one thing in, many routes out.
 */

/** Facet's SVG is 220 units tall with the body centred at y=120, so anchoring
    by that point rather than the box keeps him steady while he scales. */
const place = (cx: number, cy: number, size: number) => ({
  position: "absolute" as const,
  left: cx - size / 2,
  top: cy - size * (120 / 220),
});

const BEAM_IN = 36;
const REVEAL = 36;
const MOVE = 168;
const END = 292;

export const Intro: React.FC = () => {
  const f = useCurrentFrame();
  const bob = useBob(9, 84);
  const blink = useBlink();

  // Entrance: overshoot then settle. A plain spring reads too soft for a
  // character that is supposed to arrive as a burst of light.
  const pop = interpolate(f, [REVEAL, REVEAL + 10, REVEAL + 20, REVEAL + 30], [0, 1.22, 0.94, 1], {
    extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.out(Easing.cubic),
  });

  const cx = interpolate(f, [MOVE, MOVE + 34], [960, 610], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.inOut(Easing.cubic) });
  const cy = 560 + bob;
  const size = 400;

  const beamTip = interpolate(f, [0, BEAM_IN], [0, cx - 100], { extrapolateRight: "clamp", easing: Easing.in(Easing.quad) });
  const flash = interpolate(f, [REVEAL - 2, REVEAL + 3, REVEAL + 18], [0, 0.85, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const fanP = interpolate(f, [REVEAL + 6, REVEAL + 44], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });

  // A two-beat wave: arm up, down, up, rest.
  const waveWindow = (start: number) => {
    const t = f - start;
    if (t < 0 || t > 46) return 0;
    return Math.sin((t / 46) * Math.PI) * Math.sin((t / 46) * Math.PI * 3) * 62;
  };
  const armR = -30 - waveWindow(96) - waveWindow(232);

  const expression = f < REVEAL + 14 ? "wow" : f > 96 && f < 150 ? "cheer" : "happy";
  const lookX = f > MOVE && f < MOVE + 60 ? 4 : Math.sin(f / 44) * 3;

  // Once he steps aside for the type, the fan swings down and dims so the
  // rays pass beneath the headline instead of through it.
  const settle = interpolate(f, [MOVE, MOVE + 40], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.inOut(Easing.cubic) });
  const fanRotate = settle * 54;
  const fanFade = 0.95 - settle * 0.42;

  const bodyOut = interpolate(f, [END - 12, END + 6], [1, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const textIn = f > 178;

  return (
    <Stage>
      {/* Original score, generated by music/compose.mjs and cued to this
          scene's frame constants. Swap the file to use a licensed track. */}
      <Audio src={staticFile("music/refract-intro.wav")} />
      <AbsoluteFill style={{ opacity: bodyOut }}>
        <svg width={1920} height={1080} style={{ position: "absolute", inset: 0 }}>
          <defs>
            <linearGradient id="in-beam" x1="0" y1="0" x2={cx} y2="0" gradientUnits="userSpaceOnUse">
              <stop offset="0%" stopColor={C.white} stopOpacity={0} />
              <stop offset="70%" stopColor={C.white} stopOpacity={0.9} />
              <stop offset="100%" stopColor="#ffffff" stopOpacity={1} />
            </linearGradient>
          </defs>

          <line x1={0} y1={cy - 14} x2={beamTip} y2={cy - 14} stroke="url(#in-beam)" strokeWidth={5} strokeLinecap="round" />
          {f < REVEAL + 4 ? (
            <>
              <circle cx={beamTip} cy={cy - 14} r={22} fill={C.honey} opacity={0.3} />
              <circle cx={beamTip} cy={cy - 14} r={8} fill="#fbfff6" />
            </>
          ) : null}

          {f > REVEAL ? (
            <Fan x={cx + 96} y={cy - 8} length={780} spread={64} progress={fanP} width={7} opacity={fanFade} rotate={fanRotate} />
          ) : null}
        </svg>

        <div style={place(cx, cy, size)}>
          <div style={{ transform: `scale(${pop})`, transformOrigin: "50% 55%" }}>
            <Facet
              size={size}
              expression={expression as never}
              blink={blink}
              lookX={lookX}
              armL={-14}
              armR={armR}
              tilt={Math.sin(f / 70) * 2.5}
              glow={0.45 + flash * 0.5}
              charge={0.55 + Math.sin(f / 22) * 0.2}
              uid="intro"
            />
          </div>
        </div>

        {textIn ? (
          <div style={{ position: "absolute", left: 1010, top: 372, display: "flex", flexDirection: "column", gap: 22 }}>
            <Kicker delay={180}>Meet</Kicker>
            <Headline delay={188} size={172}>FACET</Headline>
            <div style={{ maxWidth: 620 }}>
              <Headline delay={212} size={38} weight={500} color={C.muted}>
                He takes one trade in and finds every way out.
              </Headline>
            </div>
          </div>
        ) : null}

        <AbsoluteFill style={{ background: "#f8fff0", opacity: flash, mixBlendMode: "screen", pointerEvents: "none" }} />
      </AbsoluteFill>

      {f >= END ? <EndCard delay={END} tagline="A routing exchange for Robinhood Chain." /> : null}
    </Stage>
  );
};
