import React from "react";
import { Audio, staticFile, AbsoluteFill, interpolate, useCurrentFrame, random, Easing } from "remotion";
import { Facet } from "../Mascot";
import { Stage, Headline, Kicker, EndCard, Panel, useBob, useBlink } from "../ui";
import { C, FONT, SPECTRUM } from "../theme";

/**
 * SEE THEM ON THE CURVE — 19s launch-pool film.
 *
 * Facet sweeps a prism scope across the dark and new bonding-curve tokens
 * light up. The cards carry symbols and a supply-sold bar only: no prices, no
 * dollar figures. A token still on its curve has no pool and therefore no
 * price, and the film should not imply one where the product refuses to.
 */

const T = { facet: 34, scope: 66, cards: 96, curve: 292, bullets: 168, honest: 372, end: 470 };

const TOKENS = ["ORB", "MITE", "GLYPH", "FLUX", "RUNE", "TALLY"];
const GRID = { x: 880, y: 244, w: 300, h: 192, gx: 26, gy: 24 };

const cardPos = (i: number) => ({
  left: GRID.x + (i % 3) * (GRID.w + GRID.gx),
  top: GRID.y + Math.floor(i / 3) * (GRID.h + GRID.gy),
});

/** Same procedural avatar the app derives from a contract address, since a
    launchpad token almost never ships a logo. */
const Avatar: React.FC<{ seed: string; size: number }> = ({ seed, size }) => {
  const h = Math.floor(random(seed) * 1000);
  const hue = 18 + (h % 40);
  const hue2 = 26 + ((h >> 3) % 34);
  const light = 52 + ((h >> 5) % 22);
  return (
    <span
      style={{
        width: size, height: size, borderRadius: "50%", flexShrink: 0,
        display: "inline-flex", alignItems: "center", justifyContent: "center",
        background: `linear-gradient(${h % 360}deg, hsl(${hue} 88% ${light}%), hsl(${hue2} 76% ${light - 24}%))`,
        boxShadow: "inset 0 0 0 1px rgba(255,255,255,.16)",
      }}
    />
  );
};

export const LaunchPools: React.FC = () => {
  const f = useCurrentFrame();
  const bob = useBob(8, 96);
  const blink = useBlink(47);

  const enter = interpolate(f, [T.facet, T.facet + 30], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.out(Easing.cubic) });
  const cx = 252, cy = 930 + bob;

  // The scope sweeps up and right across the grid, then holds.
  const sweep = interpolate(f, [T.scope, T.cards + 210], [-8, -46], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.inOut(Easing.quad) });
  const scopeOn = interpolate(f, [T.scope, T.scope + 18], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const outro = interpolate(f, [T.end - 14, T.end + 6], [1, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });

  const ox = cx + 118, oy = cy - 76;
  const rad = (sweep * Math.PI) / 180;
  const cone = 13 * (Math.PI / 180);

  const curveP = interpolate(f, [T.curve, T.curve + 70], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.out(Easing.cubic) });

  const bullets = [
    "Discovered from launchpad factory events.",
    "Each curve resolved from its launch mint — the one transfer from the zero address.",
    "Protocol-agnostic: it needs no launchpad's private ABI.",
  ];

  return (
    <Stage>
      {/* Original score, generated by music/compose.mjs and cued to this
          scene's frame constants. Swap the file to use a licensed track. */}
      <Audio src={staticFile("music/refract-launch-pools.wav")} />
      <AbsoluteFill style={{ opacity: outro }}>
        <svg width={1920} height={1080} style={{ position: "absolute", inset: 0 }}>
          <defs>
          </defs>
          {/* scope sweep */}
          <g opacity={scopeOn * 0.9}>
            {SPECTRUM.map((c, i) => (
              <line
                key={c}
                x1={ox} y1={oy}
                x2={ox + Math.cos(rad + (i - 2.5) * cone * 0.42) * 1500}
                y2={oy + Math.sin(rad + (i - 2.5) * cone * 0.42) * 1500}
                stroke={c}
                strokeWidth={i === 0 ? 3 : 2.2}
                opacity={0.5 - Math.abs(i - 2.5) * 0.07}
              />
            ))}
            {/* the scope itself: a prism shard he sights through */}
            <path d={`M${ox - 34} ${oy + 30} L${ox + 26} ${oy - 26} L${ox + 44} ${oy + 22} Z`} fill={C.gold} opacity={0.9} stroke={C.champagne} strokeWidth={4} strokeLinejoin="round" />
          </g>
        </svg>

        <div style={{ position: "absolute", left: cx - 140, top: cy - 153, opacity: enter }}>
          <Facet
            size={280}
            expression={f > T.cards + 40 ? "happy" : "focus"}
            blink={blink}
            lookX={4} lookY={-3}
            armL={-20} armR={-52 + Math.sin(f / 40) * 8}
            tilt={-4 + Math.sin(f / 88) * 2}
            glow={0.42} charge={0.45 + scopeOn * 0.35}
            uid="lp"
          />
        </div>

        {/* ---- copy ---- */}
        <div style={{ position: "absolute", left: 108, top: 96, width: 740 }}>
          <Kicker delay={0}>Launch pools</Kicker>
          <div style={{ marginTop: 22 }}>
            <Headline delay={8} size={92}>SEE THEM BEFORE THEY GRADUATE.</Headline>
          </div>
        </div>

        <div style={{ position: "absolute", left: 108, top: 452, width: 690, display: "flex", flexDirection: "column", gap: 20 }}>
          {bullets.map((b, i) => {
            const p = interpolate(f, [T.bullets + i * 26, T.bullets + i * 26 + 22], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.out(Easing.cubic) });
            if (p <= 0) return null;
            return (
              <div key={b} style={{ display: "flex", gap: 16, opacity: p, transform: `translateX(${(1 - p) * -18}px)` }}>
                <span style={{ width: 9, height: 9, borderRadius: 5, background: SPECTRUM[i + 1], marginTop: 12, flexShrink: 0 }} />
                <span style={{ fontFamily: FONT.body, fontSize: 26, color: C.muted, lineHeight: 1.45 }}>{b}</span>
              </div>
            );
          })}
        </div>

        {/* ---- discovered tokens ---- */}
        {TOKENS.map((sym, i) => {
          const at = T.cards + i * 30;
          const p = interpolate(f, [at, at + 24], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.out(Easing.back(1.6)) });
          if (p <= 0) return null;
          const pos = cardPos(i);
          const sold = 22 + random(`sold-${sym}`) * 64;
          const grad = sold > 78;
          const bar = interpolate(f, [at + 18, at + 54], [0, sold], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.out(Easing.cubic) });
          return (
            <div key={sym} style={{ position: "absolute", ...pos, width: GRID.w, height: GRID.h, transform: `scale(${0.86 + p * 0.14})`, opacity: Math.min(1, p) }}>
              <Panel lift={1} style={{ height: "100%", padding: "22px 24px", display: "flex", flexDirection: "column", justifyContent: "space-between" }}>
                <div style={{ display: "flex", alignItems: "center", gap: 14 }}>
                  <Avatar seed={sym} size={44} />
                  <div style={{ display: "flex", flexDirection: "column" }}>
                    <span style={{ fontFamily: FONT.display, fontSize: 28, color: C.text, fontWeight: 700 }}>{sym}</span>
                    <span style={{ fontFamily: FONT.mono, fontSize: 15, color: C.faint, letterSpacing: "0.1em" }}>
                      0x{random(`addr-${sym}`).toString(16).slice(2, 8)}…
                    </span>
                  </div>
                  <span
                    style={{
                      marginLeft: "auto", fontFamily: FONT.mono, fontSize: 13, letterSpacing: "0.14em",
                      color: grad ? C.olive : C.honey, border: `1px solid ${grad ? C.olive : C.honey}`,
                      borderRadius: 6, padding: "5px 9px", opacity: 0.9,
                    }}
                  >
                    {grad ? "GRADUATED" : "ON CURVE"}
                  </span>
                </div>
                <div>
                  <div style={{ display: "flex", justifyContent: "space-between", fontFamily: FONT.mono, fontSize: 16, color: C.faint, letterSpacing: "0.1em", marginBottom: 10 }}>
                    <span>SUPPLY SOLD</span>
                    <span style={{ color: C.muted }}>{bar.toFixed(0)}%</span>
                  </div>
                  <div style={{ height: 8, borderRadius: 4, background: "rgba(163,230,53,0.12)", overflow: "hidden" }}>
                    <div style={{ width: `${bar}%`, height: "100%", background: `linear-gradient(90deg, ${C.brass}, ${C.honey})`, borderRadius: 4 }} />
                  </div>
                </div>
              </Panel>
            </div>
          );
        })}

        {/* ---- the curve itself ---- */}
        {f > T.curve ? (
          <div style={{ position: "absolute", left: GRID.x, top: 706, width: 952 }}>
            <Panel lift={Math.min(1, curveP * 2)} style={{ padding: "24px 30px" }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 }}>
                <span style={{ fontFamily: FONT.mono, fontSize: 16, letterSpacing: "0.22em", color: C.faint }}>BONDING CURVE</span>
                <span style={{ fontFamily: FONT.mono, fontSize: 16, letterSpacing: "0.16em", color: C.olive }}>GRADUATES &#8594; UNISWAP</span>
              </div>
              <svg width={892} height={148} style={{ display: "block" }}>
                <path d="M8 138 C 300 132, 560 104, 700 58 S 830 12, 884 8" fill="none" stroke="rgba(163,230,53,0.16)" strokeWidth={3} />
                <path
                  d="M8 138 C 300 132, 560 104, 700 58 S 830 12, 884 8"
                  fill="none" stroke={C.gold} strokeWidth={4} strokeLinecap="round"
                  strokeDasharray={1000} strokeDashoffset={1000 * (1 - curveP)}
                />
                <circle cx={8 + 876 * curveP} cy={138 - 130 * Math.pow(curveP, 1.7)} r={9} fill="#fbfff6" />
                <circle cx={8 + 876 * curveP} cy={138 - 130 * Math.pow(curveP, 1.7)} r={20} fill={C.honey} opacity={0.28} />
              </svg>
            </Panel>
          </div>
        ) : null}

        {f > T.honest ? (
          <div
            style={{
              position: "absolute", left: 108, top: 702, width: 620,
              fontFamily: FONT.body, fontSize: 24, color: C.muted, lineHeight: 1.5,
              opacity: interpolate(f, [T.honest, T.honest + 22], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" }),
              borderLeft: `2px solid ${C.line}`, paddingLeft: 22,
            }}
          >
            A token still on its curve has no pool, so REFRACT shows no price. It shows
            what is provable instead: supply sold, unsold reserve, real trade counts.
          </div>
        ) : null}
      </AbsoluteFill>

      {f >= T.end ? <EndCard delay={T.end} tagline="Discovery that does not depend on one launchpad." /> : null}
    </Stage>
  );
};
