// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "../src/Verifier.sol";
import "../src/VerifierAdapter.sol";

/**
 * Verifies a proof that was generated by the actual browser build, not by the
 * node script. This closes the last gap: same circuit, same proving key, same
 * code path a user would hit, checked against the on-chain verifier.
 */
contract BrowserProofTest is Test {
    VerifierAdapter adapter;

    function setUp() public {
        adapter = new VerifierAdapter(IGroth16Verifier(address(new Groth16Verifier())));
    }

    function test_browserGeneratedProofVerifiesOnChain() public view {
        string memory raw = vm.readFile("artifacts/browser-proof.json");
        uint256[] memory f = vm.parseJsonUintArray(raw, ".flat");

        uint256[2] memory a = [f[0], f[1]];
        uint256[2][2] memory b = [[f[2], f[3]], [f[4], f[5]]];
        uint256[2] memory c = [f[6], f[7]];
        uint256[] memory input = new uint256[](6);
        for (uint256 i = 0; i < 6; i++) input[i] = f[8 + i];

        assertTrue(adapter.verifyProof(a, b, c, input), "browser proof must verify on-chain");
    }
}
