// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "../src/RefractPool.sol";
import "../src/JoinSplitVerifier.sol";
import "../src/JoinSplitAdapter.sol";

/**
 * Adversarial tests for the pool.
 *
 * `swap` hands control to two contracts whose code an attacker chooses: the
 * router payload, and `tokenOut`, whose `balanceOf` and `transfer` are
 * arbitrary code that this pool calls. Everything here tries to turn one of
 * those into more ETH leaving the pool than a proof authorised.
 *
 * The proofs are genuine, generated by circuits/jstest.mjs. Tampering is done
 * to the call rather than to the maths, because a forged proof is the one
 * attack the verifier already answers.
 */
contract PoolSecurityTest is Test {
    RefractPool pool;
    JoinSplitVerifier verifier;
    JoinSplitAdapter adapter;
    IHasher hasher;
    EvilRouter router;

    address constant DEAD = 0x000000000000000000000000000000000000dEaD;
    address constant TOKEN_OUT = 0x1111111111111111111111111111111111111111;
    address constant ATTACKER = address(0xBADBAD);

    function setUp() public {
        string memory raw = vm.readFile("artifacts/Poseidon2.json");
        bytes memory code = vm.parseJsonBytes(raw, ".bytecode");
        address h;
        assembly { h := create(0, add(code, 0x20), mload(code)) }
        hasher = IHasher(h);

        verifier = new JoinSplitVerifier();
        adapter = new JoinSplitAdapter(IGroth16JoinSplit(address(verifier)));
        deployCodeTo("PoolSecurity.t.sol:EvilToken", TOKEN_OUT);
        router = new EvilRouter(EvilToken(TOKEN_OUT));
        pool = new RefractPool(IVerifier(address(adapter)), hasher, address(router));
        EvilToken(TOKEN_OUT).setPool(address(pool));
        router.setPool(address(pool));
    }

    function _load(string memory tag)
        internal
        view
        returns (RefractPool.Proof memory p, RefractPool.TransactArgs memory a, RefractPool.ExtData memory e)
    {
        string memory raw = vm.readFile("artifacts/joinsplit-fixture.json");
        uint256[] memory f = vm.parseJsonUintArray(raw, string.concat(".", tag, ".flat"));
        p.a = [f[0], f[1]];
        p.b = [[f[2], f[3]], [f[4], f[5]]];
        p.c = [f[6], f[7]];
        a.root = bytes32(f[8]);
        a.publicAmount = f[9];
        a.extDataHash = bytes32(f[10]);
        a.inNullifiers = [bytes32(f[11]), bytes32(f[12])];
        a.outCommitments = [bytes32(f[13]), bytes32(f[14])];

        string memory b = string.concat(".", tag, ".ext");
        e.recipient = vm.parseJsonAddress(raw, string.concat(b, ".recipient"));
        e.extAmount = vm.parseJsonInt(raw, string.concat(b, ".extAmount"));
        e.relayer = vm.parseJsonAddress(raw, string.concat(b, ".relayer"));
        e.fee = vm.parseJsonUint(raw, string.concat(b, ".fee"));
        e.encryptedOutput1 = vm.parseJsonBytes(raw, string.concat(b, ".encryptedOutput1"));
        e.encryptedOutput2 = vm.parseJsonBytes(raw, string.concat(b, ".encryptedOutput2"));
    }

    function _swapData() internal view returns (RefractPool.SwapData memory sd) {
        string memory raw = vm.readFile("artifacts/joinsplit-fixture.json");
        sd.tokenOut = vm.parseJsonAddress(raw, ".swap.ext.swap.tokenOut");
        sd.amountOutMin = vm.parseJsonUint(raw, ".swap.ext.swap.amountOutMin");
        sd.recipient = vm.parseJsonAddress(raw, ".swap.ext.swap.recipient");
        sd.routerCalldata = vm.parseJsonBytes(raw, ".swap.ext.swap.routerCalldata");
    }

    function _fund() internal {
        (RefractPool.Proof memory p, RefractPool.TransactArgs memory a, RefractPool.ExtData memory e) =
            _load("deposit");
        pool.transact{value: 3.7 ether}(p, a, e);
    }

    /* ------------------------------------------------------- the drain tests */

    /**
     * The headline property. A swap may move exactly the ETH its proof
     * authorised and not one wei more, however hostile the token and the
     * router are.
     */
    function test_swapCannotMoveMoreEthThanTheProofAuthorises() public {
        _fund();
        assertEq(address(pool).balance, 3.7 ether);

        (RefractPool.Proof memory p, RefractPool.TransactArgs memory a, RefractPool.ExtData memory e) =
            _load("swap");
        RefractPool.SwapData memory sd = _swapData();

        // Both hostile contracts armed: the token reenters on every hook it
        // gets, and the router tries to call back in for more.
        EvilToken(TOKEN_OUT).arm(p, a, e, sd);
        router.arm(p, a, e, sd);

        pool.swap(p, a, e, sd);

        assertEq(address(pool).balance, 2.5 ether, "only the routed 1.2 ETH may leave");
        assertGt(EvilToken(TOKEN_OUT).reentryAttempts(), 0, "the token did try to reenter");
        assertEq(EvilToken(TOKEN_OUT).reentrySuccesses(), 0, "and every attempt failed");
        assertGt(router.reentryAttempts(), 0, "the router did try to reenter");
        assertEq(router.reentrySuccesses(), 0, "and every attempt failed");
    }

    /** The pool may call exactly one address, no matter what the payload says. */
    function test_payloadCannotRedirectTheCall() public {
        _fund();
        (RefractPool.Proof memory p, RefractPool.TransactArgs memory a, RefractPool.ExtData memory e) =
            _load("swap");
        RefractPool.SwapData memory sd = _swapData();

        // A payload that would drain the pool if the target were choosable.
        // It goes to the router regardless, which has no such function.
        sd.routerCalldata = abi.encodeWithSignature("sweepTo(address)", ATTACKER);

        // The hash binds the payload, so a rewritten one fails before any call.
        vm.expectRevert(RefractPool.BadProof.selector);
        pool.swap(p, a, e, sd);
        assertEq(address(pool).balance, 3.7 ether, "nothing moved");
    }

    /** The pool never approves anything, so a payload has no allowance to spend. */
    function test_poolGrantsNoAllowances() public {
        _fund();
        (RefractPool.Proof memory p, RefractPool.TransactArgs memory a, RefractPool.ExtData memory e) =
            _load("swap");
        RefractPool.SwapData memory sd = _swapData();
        pool.swap(p, a, e, sd);
        assertEq(
            EvilToken(TOKEN_OUT).allowance(address(pool), address(router)),
            0,
            "an allowance would let a crafted payload move the pool's tokens"
        );
    }

    /** A token that lies about delivery cannot short the spender. */
    function test_lyingTokenCannotShortTheRecipient() public {
        _fund();
        (RefractPool.Proof memory p, RefractPool.TransactArgs memory a, RefractPool.ExtData memory e) =
            _load("swap");
        RefractPool.SwapData memory sd = _swapData();
        EvilToken(TOKEN_OUT).setUnderdeliver(true);

        vm.expectRevert(RefractPool.InsufficientOutput.selector);
        pool.swap(p, a, e, sd);
        assertEq(address(pool).balance, 3.7 ether, "a failed swap moves nothing");
    }

    /** A token whose transfer quietly fails must revert the whole swap. */
    function test_failingTransferRevertsTheSwap() public {
        _fund();
        (RefractPool.Proof memory p, RefractPool.TransactArgs memory a, RefractPool.ExtData memory e) =
            _load("swap");
        RefractPool.SwapData memory sd = _swapData();
        EvilToken(TOKEN_OUT).setRefuseTransfer(true);

        vm.expectRevert(RefractPool.TransferFailed.selector);
        pool.swap(p, a, e, sd);
        assertEq(address(pool).balance, 3.7 ether, "a failed swap moves nothing");
    }

    /** A router that keeps the ETH and sends nothing back still cannot profit. */
    function test_routerThatDeliversNothingFailsTheSwap() public {
        _fund();
        (RefractPool.Proof memory p, RefractPool.TransactArgs memory a, RefractPool.ExtData memory e) =
            _load("swap");
        RefractPool.SwapData memory sd = _swapData();
        router.setDeliverNothing(true);

        vm.expectRevert(RefractPool.InsufficientOutput.selector);
        pool.swap(p, a, e, sd);
        assertEq(address(pool).balance, 3.7 ether, "the state is rolled back with it");
    }

    /** Nobody may push ETH in except the router mid-swap. */
    function test_onlyRouterMaySendEth() public {
        vm.deal(ATTACKER, 5 ether);
        vm.prank(ATTACKER);
        (bool ok, ) = address(pool).call{value: 1 ether}("");
        assertFalse(ok, "deposits must go through a proof");
    }

    /** Total ETH out can never exceed total ETH in. */
    function test_poolNeverPaysOutMoreThanItTookIn() public {
        _fund();
        (RefractPool.Proof memory p, RefractPool.TransactArgs memory a, RefractPool.ExtData memory e) =
            _load("swap");
        RefractPool.SwapData memory sd = _swapData();
        EvilToken(TOKEN_OUT).arm(p, a, e, sd);
        router.arm(p, a, e, sd);
        pool.swap(p, a, e, sd);

        uint256 paidIn = 3.7 ether;
        uint256 paidOut = router.ethReceived() + DEAD.balance;
        assertLe(paidOut, paidIn, "more left the pool than ever entered it");
    }
}

/* ---------------------------------------------------------------- hostiles */

/**
 * A token whose every hook is attacker code. The pool calls `balanceOf` twice
 * and `transfer` once, and each is a chance to reenter.
 */
contract EvilToken {
    mapping(address => uint256) public balanceOf;
    mapping(address => mapping(address => uint256)) public allowance;

    address public pool;
    bool public underdeliver;
    bool public refuseTransfer;
    bool private armed;
    uint256 public reentryAttempts;
    uint256 public reentrySuccesses;

    RefractPool.Proof private p;
    RefractPool.TransactArgs private a;
    RefractPool.ExtData private e;
    RefractPool.SwapData private sd;

    function setPool(address p_) external { pool = p_; }
    function setUnderdeliver(bool v) external { underdeliver = v; }
    function setRefuseTransfer(bool v) external { refuseTransfer = v; }

    function arm(
        RefractPool.Proof calldata p_,
        RefractPool.TransactArgs calldata a_,
        RefractPool.ExtData calldata e_,
        RefractPool.SwapData calldata sd_
    ) external {
        p = p_; a = a_; e = e_; sd = sd_; armed = true;
    }

    function mint(address to, uint256 amount) external {
        balanceOf[to] += amount / (underdeliver ? 4 : 1);
        _tryReenter();
    }

    function transfer(address to, uint256 amount) external returns (bool) {
        _tryReenter();
        if (refuseTransfer) return false;
        if (balanceOf[msg.sender] < amount) return false;
        balanceOf[msg.sender] -= amount;
        balanceOf[to] += amount;
        return true;
    }

    /// Every reentry the pool allows is a second spend of notes already spent.
    function _tryReenter() internal {
        if (!armed || pool == address(0)) return;
        reentryAttempts++;
        try RefractPool(payable(pool)).swap(p, a, e, sd) {
            reentrySuccesses++;
        } catch {}
        reentryAttempts++;
        try RefractPool(payable(pool)).transact(p, a, e) {
            reentrySuccesses++;
        } catch {}
    }
}

/** A router that takes the ETH and tries to come back for more. */
contract EvilRouter {
    EvilToken public token;
    address public pool;
    uint256 public rate = 1000;
    bool public deliverNothing;
    bool private armed;
    uint256 public ethReceived;
    uint256 public reentryAttempts;
    uint256 public reentrySuccesses;

    RefractPool.Proof private p;
    RefractPool.TransactArgs private a;
    RefractPool.ExtData private e;
    RefractPool.SwapData private sd;

    constructor(EvilToken t) { token = t; }
    function setPool(address p_) external { pool = p_; }
    function setDeliverNothing(bool v) external { deliverNothing = v; }

    function arm(
        RefractPool.Proof calldata p_,
        RefractPool.TransactArgs calldata a_,
        RefractPool.ExtData calldata e_,
        RefractPool.SwapData calldata sd_
    ) external {
        p = p_; a = a_; e = e_; sd = sd_; armed = true;
    }

    function swapExactEthForToken() external payable {
        ethReceived += msg.value;
        if (armed && pool != address(0)) {
            reentryAttempts++;
            try RefractPool(payable(pool)).swap(p, a, e, sd) {
                reentrySuccesses++;
            } catch {}
        }
        if (!deliverNothing) token.mint(msg.sender, msg.value * rate);
    }

    receive() external payable { ethReceived += msg.value; }
}
