// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "../src/RefractShielded.sol";

/// Accepts anything. Lets the pool's own logic be tested independently of the
/// circuit, which is generated separately.
contract MockVerifier is IVerifier {
    bool public ok = true;
    function setOk(bool v) external { ok = v; }
    function verifyProof(uint256[2] calldata, uint256[2][2] calldata, uint256[2] calldata, uint256[] calldata)
        external view returns (bool) { return ok; }
}

contract MockRouter {
    receive() external payable {}
    function swap(address payable to, uint256 out) external payable {
        (bool s, ) = to.call{value: out}("");
        require(s, "router pay failed");
    }
}

contract RefractShieldedTest is Test {
    RefractShielded pool;
    MockVerifier verifier;
    MockRouter router;
    IHasher hasher;

    address alice = address(0xA1);
    address bob = address(0xB2);
    uint256 constant DENOM = 1 ether;

    function setUp() public {
        // Deploy circomlib's Poseidon from generated bytecode. The tree must
        // hash identically here and in the circuit.
        string memory raw = vm.readFile("artifacts/Poseidon2.json");
        bytes memory code = vm.parseJsonBytes(raw, ".bytecode");
        address h;
        assembly { h := create(0, add(code, 0x20), mload(code)) }
        require(h != address(0), "poseidon deploy failed");
        hasher = IHasher(h);

        verifier = new MockVerifier();
        router = new MockRouter();
        pool = new RefractShielded(verifier, hasher, address(router), address(0), DENOM);

        vm.deal(alice, 100 ether);
        vm.deal(bob, 100 ether);
        vm.deal(address(router), 100 ether);
    }

    /* --------------------------------------------------------------- hashing */

    function test_onchainPoseidonMatchesJs() public view {
        // Reference vector from circomlibjs. If this drifts, every proof the
        // browser generates would be rejected on-chain.
        uint256 expected =
            7853200120776062878684798364095072458815029376092732009249414926327459813530;
        uint256[2] memory pair = [uint256(1), uint256(2)];
        assertEq(hasher.poseidon(pair), expected, "poseidon(1,2) must match circomlibjs");
    }

    /* -------------------------------------------------------------- deposits */

    function test_depositInsertsAndMovesRoot() public {
        bytes32 root0 = pool.getLastRoot();
        bytes32 c1 = _commitment(1);

        vm.prank(alice);
        pool.deposit{value: DENOM}(c1);

        assertEq(address(pool).balance, DENOM);
        assertEq(pool.nextIndex(), 1);
        assertTrue(pool.getLastRoot() != root0, "root must advance");
        assertTrue(pool.isKnownRoot(root0), "old root stays valid for in-flight proofs");
    }

    function test_depositRejectsWrongValue() public {
        vm.prank(alice);
        vm.expectRevert(RefractShielded.WrongValue.selector);
        pool.deposit{value: 0.5 ether}(_commitment(1));
    }

    function test_depositRejectsDuplicateCommitment() public {
        bytes32 c = _commitment(7);
        vm.prank(alice);
        pool.deposit{value: DENOM}(c);

        vm.prank(bob);
        vm.expectRevert(RefractShielded.CommitmentUsed.selector);
        pool.deposit{value: DENOM}(c);
    }

    function test_depositRejectsOutOfField() public {
        vm.prank(alice);
        vm.expectRevert(RefractShielded.NotInField.selector);
        pool.deposit{value: DENOM}(bytes32(type(uint256).max));
    }

    function test_bareSendRejected() public {
        vm.prank(alice);
        (bool ok, ) = address(pool).call{value: 1 ether}("");
        assertFalse(ok, "only deposit() may add funds");
    }

    /* ------------------------------------------------------------ withdrawal */

    function test_withdrawPaysRecipient() public {
        _fund(3);
        bytes32 root = pool.getLastRoot();

        pool.withdraw(_a(), _b(), _c(), root, _nullifier(1), payable(bob), payable(address(0)), 0);

        assertEq(bob.balance, 100 ether + DENOM);
        assertTrue(pool.nullifierSpent(_nullifier(1)));
    }

    function test_withdrawRejectsDoubleSpend() public {
        _fund(3);
        bytes32 root = pool.getLastRoot();
        pool.withdraw(_a(), _b(), _c(), root, _nullifier(1), payable(bob), payable(address(0)), 0);

        vm.expectRevert(RefractShielded.NullifierUsed.selector);
        pool.withdraw(_a(), _b(), _c(), root, _nullifier(1), payable(bob), payable(address(0)), 0);
    }

    function test_withdrawRejectsBadProof() public {
        _fund(2);
        bytes32 root = pool.getLastRoot();
        verifier.setOk(false);
        vm.expectRevert(RefractShielded.BadProof.selector);
        pool.withdraw(_a(), _b(), _c(), root, _nullifier(1), payable(bob), payable(address(0)), 0);
    }

    function test_withdrawRejectsUnknownRoot() public {
        _fund(2);
        vm.expectRevert(RefractShielded.UnknownRoot.selector);
        pool.withdraw(_a(), _b(), _c(), keccak256("not a root"), _nullifier(1), payable(bob), payable(address(0)), 0);
    }

    function test_withdrawRelayerFeeSplits() public {
        _fund(3);
        address relayer = address(0xBEEF);
        uint256 fee = 0.05 ether;

        pool.withdraw(_a(), _b(), _c(), pool.getLastRoot(), _nullifier(1), payable(bob), payable(relayer), fee);

        assertEq(bob.balance, 100 ether + DENOM - fee);
        assertEq(relayer.balance, fee, "relayer paid for covering gas");
    }

    function test_withdrawRejectsFeeOverDenomination() public {
        _fund(2);
        bytes32 root = pool.getLastRoot();
        vm.expectRevert(RefractShielded.FeeTooHigh.selector);
        pool.withdraw(_a(), _b(), _c(), root, _nullifier(1), payable(bob), payable(bob), DENOM + 1);
    }

    /* ------------------------------------------------------------ root window */

    function test_oldRootExpiresAfterHistoryFills() public {
        bytes32 oldRoot = pool.getLastRoot();
        // ROOT_HISTORY is 30; push past it.
        for (uint256 i = 1; i <= 31; i++) {
            vm.deal(alice, DENOM);
            vm.prank(alice);
            pool.deposit{value: DENOM}(_commitment(i));
        }
        assertFalse(pool.isKnownRoot(oldRoot), "root should age out of the window");
        assertTrue(pool.isKnownRoot(pool.getLastRoot()));
    }

    /* ------------------------------------------------------------- integrity */

    function test_noAdminPathExists() public {
        _fund(5);
        uint256 held = address(pool).balance;

        // There is no owner, no operator, and no privileged function. The only
        // exits are withdraw() and shieldedSwap(), both gated on a proof.
        (bool ok, ) = address(pool).call(abi.encodeWithSignature("owner()"));
        assertFalse(ok, "no owner() to hold a key");
        (ok, ) = address(pool).call(abi.encodeWithSignature("transferOwnership(address)"));
        assertFalse(ok, "no ownership to transfer");

        assertEq(address(pool).balance, held, "funds untouched");
    }

    function testFuzz_nullifierCannotBeReused(bytes32 nh) public {
        vm.assume(nh != bytes32(0));
        _fund(4);
        bytes32 root = pool.getLastRoot();

        pool.withdraw(_a(), _b(), _c(), root, nh, payable(bob), payable(address(0)), 0);
        vm.expectRevert(RefractShielded.NullifierUsed.selector);
        pool.withdraw(_a(), _b(), _c(), root, nh, payable(bob), payable(address(0)), 0);
    }

    /* --------------------------------------------------------------- helpers */

    function _fund(uint256 n) internal {
        for (uint256 i = 1; i <= n; i++) {
            vm.deal(alice, DENOM);
            vm.prank(alice);
            pool.deposit{value: DENOM}(_commitment(i));
        }
    }

    function _commitment(uint256 seed) internal pure returns (bytes32) {
        return bytes32(uint256(keccak256(abi.encode("commit", seed))) % 21888242871839275222246405745257275088548364400416034343698204186575808495617);
    }

    function _nullifier(uint256 seed) internal pure returns (bytes32) {
        return bytes32(uint256(keccak256(abi.encode("null", seed))) % 21888242871839275222246405745257275088548364400416034343698204186575808495617);
    }

    function _a() internal pure returns (uint256[2] memory) { return [uint256(1), uint256(2)]; }
    function _b() internal pure returns (uint256[2][2] memory) { return [[uint256(1), uint256(2)], [uint256(3), uint256(4)]]; }
    function _c() internal pure returns (uint256[2] memory) { return [uint256(5), uint256(6)]; }
}
